name: Build tonlib MacOS

on:
  push:
    branches:
    - tonlib

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
      - name: Check out source code
        uses: actions/checkout@master
        
      - name: Fetch TON repo
        run: |
          cd ..
          git clone --recursive https://github.com/ton-blockchain/ton
        
      - name: Build tonlibjson
        run: |
          cd ..
          mkdir build
          cd build
          cmake ../ton -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl
          cmake --build . --target tonlibjson
          
      - name: Copy built lib
        run: |
          cp ../build/tonlib/libtonlib* lib/darwin
          
      - name: Commit updated MacOS tonlib files
        env:
         GITHUB_TOKEN: ${{ secrets.github_token }}
         COMMIT_MSG: |
           Update MacOS tonlib
           skip-checks: true
        run: |
          # Hard-code user configuration
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Checkout the branch so we can push back to it
          git checkout tonlib
          git add .
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin tonlib)
